# ~/.GH/Qompass/nur-packages/.github/workflows/build.yml
# ------------------------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

name: "Build and Test"
on:
  pull_request:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  tests:
    runs-on: self-hosted
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-linux]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          accept-flake-config = true
    
    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      if: ${{ vars.CACHIX_NAME != '' }}
      with:
        name: ${{ vars.CACHIX_NAME }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Build all packages
      run: |
        nix-build --no-out-link --system ${{ matrix.system }} default.nix
    
    - name: Run package tests
      run: |
        nix-instantiate --eval --strict --json -A lib.tests default.nix
