name: ci
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --print-build-logs
